kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: itx-maps
  namespace: cp4i
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
